Define PROPERTY_NAME pathbox.co

<VirtualHost *:80>
		ServerName www.${PROPERTY_NAME}
		Redirect permanent / https://${PROPERTY_NAME}/
</VirtualHost>


<VirtualHost *:80>
    ServerAdmin caspar.wrede@gmail.com
    ServerName ${PROPERTY_NAME}
    #ServerAlias www.${PROPERTY_NAME}

   WSGIScriptAlias / /var/www/${PROPERTY_NAME}/deployment/apache_conf.wsgi
   <Directory /var/www/${PROPERTY_NAME}/>
        Order allow,deny
        Allow from all
   </Directory>

   Alias /static /var/www/${PROPERTY_NAME}/static
   <Directory /var/www/${PROPERTY_NAME}/static/>
        Order allow,deny
        Allow from all
        ExpiresActive on
        ExpiresByType text/css "access 1 month"
        ExpiresByType text/x-javascript "access 1 month"
        ExpiresByType text/javascript "access plus 1 week"
        ExpiresByType application/javascript "access plus 1 week"
   </Directory>

   ErrorLog ${APACHE_LOG_DIR}/${PROPERTY_NAME}-error.log
   LogLevel warn
   CustomLog ${APACHE_LOG_DIR}/${PROPERTY_NAME}-access.log combined

	 ErrorDocument 500 /maintenance.htm
   ErrorDocument 502 /maintenance.htm
   ErrorDocument 503 /maintenance.htm
   ErrorDocument 504 /maintenance.htm

</VirtualHost>
